### ISSUE TITLE
How can I use django-nose throug nosetests and/or setup.py nosetests?

### ISSUE THREAD

**Issue by WoLpH** [django-nose/django-nose#140]
It seems that it only works through `manage.py test`, is there any way to run it from `nosetests` instead?

**Comment by jwhitlock** [comment]
For my projects, I write a Makefile, so that my command is `make test` to run the tests.  See the [makefile](https://github.com/django-nose/django-nose/blob/master/Makefile) for some ideas.

I don't think we'll do this one - the project already does too much beyond "nosetest your Django code".  If you want a nose plugin project that loads Django settings, feel free to call it nose-django and borrow code.  ``DjangoSetUpPlugin`` in plugin.py might be a good starting place.

**Comment by jwhitlock** [comment]
Also, check out https://github.com/nosedjango/nosedjango
