### ISSUE TITLE
Running nosetests leads to error

### ISSUE THREAD

**Issue by SciF0r** [django-nose/django-nose#172]
Hi,

when I rum nosetests, the following happens:

<pre>
# DJANGO_SETTINGS_MODULE=custom_horizon.settings nosetests
[...]
ImportError: Could not import settings 'custom_horizon.settings' (Is it on sys.path? Is there an import error in the settings file?): cannot import name auth
[...]
</pre>

Is there anything special with the paths when using nosetests? A VENV is enabled and the application delivers the web application correctly.

Thank you & kind regards,
Denis

**Comment by jwhitlock** [comment]
The correct way to run tests with `django-nose` is to call `python manage.py test`.  I make manage.py executable, so that I just run `./manage,py test`.  I don't think you'll ever get it running by calling `nosetests` directly.

`django-nose` does many things to get Django tests to run like a nose test suite, such as:

* Adds plugins like `DjangoSetUpPlugin` that initializes the Django environment
* Converts Django test options to nose-equivalent options
* Converts the command line from `./manage.py test ...` to `nosetests ...` before calling the nose test runner
