### ISSUE TITLE
--with-coverage starts going after models are already imported

### ISSUE THREAD

**Issue by jbalogh** [django-nose/django-nose#2]
Coverage-tracking should start immediately, or else it looks like your models didn't get run at all.

**Comment by vccabral** [comment]
@yuriiz , I am running into the same problem. 

with 
    django-nose==1.3
    nose==1.3.4

**Comment by vccabral** [comment]
@yuriiz I used python's reload module and it fixed my coverage report. 

reload('app.models.*')

**Comment by AusIV** [comment]
I'm still seeing this issue:

nose==1.3.6
django-nose==1.4
Django==1.8.1

**Comment by jwhitlock** [comment]
This will happen from time to time as Django changes how apps are loaded.  See #180 for the current incarnation.  Leaving this old bug closed.

**Comment by anentropic** [comment]
I'm trying to get the 'external coverage' workaround working... but when I `coverage run manage.py test` no `.coverage` file is output.

If I do `coverage run manage.py shell` and run some code then I do get the file.

So I assume django-nose is always overriding the output options for coverage.

If I do `coverage run manage.py test --with-coverage` then I get the file, but I assume this is the 'internal' django-nose coverage rather than the external one.

**Comment by anentropic** [comment]
sorry, my problem was due to use of libfaketime's `reexec_if_needed` method https://github.com/simon-weber/python-libfaketime/blob/master/libfaketime/__init__.py ...coverage loses control of the process, code in coverage's `try/finally` block, where the report is saved, never get to run (!)
