### ISSUE TITLE
New Release to fix 1.8 transaction issues.

### ISSUE THREAD

**Issue by seanbrant** [django-nose/django-nose#232]
Any chance a new release can be created with the fixes from https://github.com/django-nose/django-nose/commit/573231d9f9aa2b0e363ce28b58965f66f7a69818?

**Comment by ferenc-radius** [comment]
+1

**Comment by clintonb** [comment]
We at edX would also appreciate a new release.

**Comment by adandan01** [comment]
+1

**Comment by clintonb** [comment]
@erikrose @jbalogh @jwhitlock any plans for a new release anytime soon? Do you need help with any tasks before the release?

**Comment by jwhitlock** [comment]
I was planning on a release when the issues attached to https://github.com/django-nose/django-nose/milestones/v1.4.2 are fixed.  I'm a month behind there, so I may release what we have so far and rename it to the v1.4.3 milestone.

However, I do want to update the docs to recommend against using REUSE_DB=1, and that it may be moved out of the main repo in the future.

Even with the fix in 573231d, the most reliable way to run django-nose is **without** REUSE_DB=1.  There are [many, many issues](https://github.com/django-nose/django-nose/milestones/Fix%20REUSE_DB=1) that appear to be caused by it.  I don't believe it will work reliably without a significant rewrite, and even then, it may just be too much magic.

**Comment by dpoirier** [comment]
My 2 cents: I sympathize with the problems REUSE_DB=1 can cause, but the significant speedup it offers makes it bearable to run tests frequently during development on some of my projects, and is really the only feature of django-nose I typically use.

**Comment by jwhitlock** [comment]
[v1.4.2](https://pypi.python.org/pypi/django-nose/1.4.2) released, includes 573231d.  Thank you for your patience.
