### ISSUE TITLE
Add flag to switch database engine

### ISSUE THREAD

**Issue by jlward** [django-nose/django-nose#243]
Hello,

We are currently using django 1.4 (working on upgrading to 1.8) and the latest version of nose and django-nose. I am looking for a plugin that can switch the database engine. I'd be willing to write it, but I don't really have a good idea of where to start (or if django-nose could handle such a plugin). 

Basically we don't want to muck up `settings.py` with test only stuff. So I want to, for example, say in `settings.py` that I am using `mysql` but when testing do something like `./manage.py test --engine=sqlite3` and the tests are now using sqlite.

Let me know if there is anything else I can provide.

**Comment by jwhitlock** [comment]
I doubt that this will be a django-nose feature.  There are too many details around database setup in tests for a simple interface to "just work".

In past projects, I did go ahead and muck with settings.py:

```python
if 'test' in sys.argv:
    DATABASES['default'] = {'ENGINE': 'django.db.backends.sqlite3'}
```
I've moved away from this, because I got into situations where the tests pass but production fails. I now use the same engine in testing and production, because there are subtle differences between SQLite and PostgreSQL.

You may also be interested in [dj-database-url](https://github.com/kennethreitz/dj-database-url), which allows you to set the database connection string from an environment variable.  See [.travis.yml](https://github.com/django-nose/django-nose/blob/master/.travis.yml) for how django-nose uses these to test against multiple database engines.

**Comment by jlward** [comment]
Thanks for the quick reply :) Looks like my best bet will be to muck around with `settings.py`.
