### ISSUE TITLE
Doesnt work with django_jenkins on Django 1.8+

### ISSUE THREAD

**Issue by mic159** [django-nose/django-nose#257]
Currently, when trying to run the `./manage.py jenkins` command, it gets this error:

```
argparse.ArgumentError: argument -l/--debug: conflicting option string(s): --debug
```

Because both `django_nose` and `django_jenkins` define a `--debug` option.

```
django-jenkins==0.18.0
django-nose==1.4.3
```

**Comment by jwhitlock** [comment]
If I knew how to solve this, it would probably fix #156 as well.

**Comment by mic159** [comment]
I think the fix would be to check if the option is already present before adding it to the parser in add_arguments.

Unfortunately it looks like django-nose can't fix this, as it is the first one to register the option.
The fix would need to be in django-jenkins but they say they won't fix: https://github.com/kmmbvnr/django-jenkins/issues/324

Does anyone know of another way to fix this?

**Comment by jwhitlock** [comment]
If you subclass [NoseTestSuiteRunner](https://github.com/django-nose/django-nose/blob/master/django_nose/runner.py#L422), and add ``--debug`` to [``django_opts``](https://github.com/django-nose/django-nose/blob/master/django_nose/runner.py#L86), you might remove the conflict. You'll need to set [TEST_RUNNER](https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-TEST_RUNNER) to use your new runner.

Or, use a test method that works with django-jenkins.

**Comment by jwhitlock** [comment]
I dug in a little more.  The ``./manage.py jenkins`` command includes an ``add_arguments`` method that adds the ``--debug`` option:

https://github.com/kmmbvnr/django-jenkins/blob/master/django_jenkins/management/commands/jenkins.py#L79-L107

Adding ``--debug`` to ``django_opts`` won't help, because it won't prevent that option being added to the parser in our ``add_arguments`` method.  We'd need a new option, for just this case, to blacklist nose options.

Your best option may be to make a local copy of ``jenkins.py`` (``myjenkins.py``?) for your own management command, which doesn't include the offending ``add_argument("--debug"...)``
