### ISSUE TITLE
Is lib compatible with Django 2.0?

### ISSUE THREAD

**Issue by sp1rs** [django-nose/django-nose#296]
Is `django-nose` compatible with `Django 2.0`?

**Comment by jwhitlock** [comment]
The tests run successfully against Django 2.0. I'll update the docs.

**Comment by jwhitlock** [comment]
Looking again, Django 2.0 is shown as supported in the master branch, but there was no release since there were no code changes. I'm looking to see what effort is needed to support 2.1, and I hope to issue a minor release. A major release is also due, to drop support before Django 1.11

Also, I'm the sole maintainer of the project, and I'm not using it anymore. django-nose is in maintenance mode, and has bugs that probably won't be fixed. I'm using pytest for other projects. If you are a happy user of django-nose, don't feel like you must switch, but I wouldn't advise using it for a new project.

**Comment by jwhitlock** [comment]
Release v1.4.6 - https://pypi.org/project/django-nose/1.4.6/
