### ISSUE TITLE
parses long options with no equals sign incorrectly

### ISSUE THREAD

**Issue by akaihola** [django-nose/django-nose#7]
Python's optparse accepts long options also without the equals sign (e.g. `--verbose 2`). Django-nose fails to strip out the values of such Django options when creating the nose command line:

    $ ./manage.py test --verbosity 0
    ======================================================================
    ERROR: Failure: OSError (No such file /home/akaihola/testproject/0)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/pymodules/python2.6/nose/failure.py", line 39, in runTest
        raise self.exc_class(self.exc_val)
    OSError: No such file /home/akaihola/testproject/0
    
    ----------------------------------------------------------------------
    Ran 20 tests in 2.844s
    
    FAILED (errors=1)

To solve this "correctly", some serious hacking with optparse is probably needed. Or, known Django options with arguments could be handled specially.

Or maybe it would be possible to "merge" Django's and nose's option parsers?

**Comment by jwhitlock** [comment]
It's been a few years, but this is still broken for me.  @camilonova, any interest in submitting a PR against current master?

**Comment by camilonova** [comment]
@jwhitlock Sorry pal, It's been a while, someone else should take care of it.

**Comment by jwhitlock** [comment]
@camilonova no problem - thanks for the original code, it's a good start.

**Comment by jwhitlock** [comment]
I left this comment on [issue 142](https://github.com/django-nose/django-nose/issues/142#issuecomment-146214535), but this might be a better place, so duplicating.

I started to dive into this, and the fix will be longer than expected, so bumping to v1.4.3.

Short version: using ``--option value`` probably won't work (yet), but ``--option=value`` might.

Longer version:

Command line parsing is complicated:

1. django-nose merges nose parse options with Django parse options.  There is a different strategy for Django 1.6 and earlier (using ``optparse``) from Django 1.7 and later (using ``argparse``).
2. Django's management command framework parses the command line
3. Django's test command class interprets some, but not all, of the command line options
4. django-nose reformats the command-line arguments to modify Django-specific options
5. nose's command line parser re-parses the reformatted command-line arguments

The problem is that Django likes ``--option value`` (and this is what ``./manage.py test --help`` will show), but nose likes ``--option=value``.  We're already manipulating the command-line args in step 4, to make things like ``verbosity`` work,  but something more generic is needed for other options with values.  Ideally, we could pass the results of Django's command line parsing to nose and skip the re-parsing steps (4 and 5), but I'm not sure if nose has the right hooks, and it may cause other issues.

**Comment by jagguli** [comment]
I had this same error, somehow removing .noseids fixed it

```
- TRACEBACK --------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/usr/lib/python2.7/site-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
OSError: No such file /home/steven/test/testproj/3
--------------------------------------------------------------------------------
```
